#!/bin/bash
#This is a script to backup created text files of different system information

#Prints the amount of free memory on the system and saves
free -h > ~/backups/freemem/free_mem.txt
#Prints disk usage and saves
du -h > ~/backups/diskuse/disk_usage.txt
#Lists all open files and saves
lsof > ~/backups/openlist/open_list.txt
#Prints file system disk space statistics and saves
df -h > ~/backups/freedisk/free_disk.txt
